<a href="https://colab.research.google.com/github/tackulus/229351/blob/main/610510531_LAB06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ปฏิบัติการครั้งที่ 6 กระบวนวิชา 229351 Statistical Learning for Data Science

คำชี้แจง

ให้เริ่มทำปฏิบัติการจาก colab notebook ที่กำหนดให้ จากนั้นเลือก File -> Download .ipynb

In [1]:
# import module ที่ต้องใช้
import numpy as np
import pandas as pd
from scipy import stats

# Download the file
!wget -O Auto.csv http://www.donlapark.cmustat.com/229351/data/Auto.csv

--2021-01-16 15:02:07--  http://www.donlapark.cmustat.com/229351/data/Auto.csv
Resolving www.donlapark.cmustat.com (www.donlapark.cmustat.com)... 150.107.31.67
Connecting to www.donlapark.cmustat.com (www.donlapark.cmustat.com)|150.107.31.67|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18079 (18K) [text/csv]
Saving to: ‘Auto.csv’

Auto.csv            100%[===================>]  17.66K  70.4KB/s    in 0.3s    

2021-01-16 15:02:08 (70.4 KB/s) - ‘Auto.csv’ saved [18079/18079]



In [2]:
# อ่านไฟล์ csv ก่อนเพื่อหา missing values
auto_df = pd.read_csv('Auto.csv',na_values=["?"])

# ลบแถวที่มี missing values
auto_df = auto_df.dropna()
auto_df.head()

mpg  cylinders  displacement  ...  year  origin                       name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino

[5 rows x 9 columns]

In [3]:
#จากคราวที่แล้ว

# β₀
beta_0 = 39.9359

# β₁
beta_1 = -0.1578


# SE(β₀)
SE_beta_0 = 0.717

# SE(β₁)
SE_beta_1 = 0.006

####คำนวณ t-statistic ของ $\hat{\beta}_0$ และ $\hat{\beta}_1$

$$t = \frac{\hat{\beta}_i-0}{\text{SE}(\hat{\beta}_i)}, \ \ \ \ \ i=0,1$$



In [5]:
# TODO: t-statistic given by t = (β - 0) / SE(β)

t_beta_0 = beta_0 / SE_beta_0

t_beta_1 = beta_1 / SE_beta_1

In [9]:
# Run the following code to compute the p-values

# p-value of t_beta_0
p_beta_0 = 2*(1 - stats.t.cdf(auto_df.shape[0], np.abs(t_beta_0)))

# p-value of t_beta_1
p_beta_1 = 2*(1 - stats.t.cdf(auto_df.shape[0], np.abs(t_beta_1)))

print(f"p-value t_beta_0 : {p_beta_0}")
print(f"p-value t_beta_1 : {p_beta_1}")

p-value t_beta_0 : 0.0
p-value t_beta_1 : 0.0


###Exercise: สามารถสรุปได้หรือไม่ว่า $\beta_0\not= 0 $ และ $\beta_1\not= 0 $ เพราะเหตุใด

ที่ระดับนัยสำคัญ $\alpha = 0.05$

ค่า p-value ของแต่ละตัวมีค่าน้อยกว่า 0.05 จึงปฎิเสธสมมติฐาน

ดังนั้น $\beta_0\neq 0 $ และ $\beta_1\neq 0 $

## Multivariate Linear Regression (การถดถอยเชิงเส้นพหุ)

### ตัวแปรต่าง ๆ มีดังนี้
mpg

    miles per gallon
cylinders

    Number of cylinders between 4 and 8
displacement

    Engine displacement (cu. inches)
horsepower

    Engine horsepower
weight

    Vehicle weight (lbs.)
acceleration

    Time to accelerate from 0 to 60 mph (sec.)
year

    Model year (modulo 100)
origin

    Origin of car (1. American, 2. European, 3. Japanese)
name

    Vehicle name


In [10]:
auto_df = auto_df.drop(['name', 'origin'],axis=1)

auto_df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year
0  18.0          8         307.0       130.0    3504          12.0    70
1  15.0          8         350.0       165.0    3693          11.5    70
2  18.0          8         318.0       150.0    3436          11.0    70
3  16.0          8         304.0       150.0    3433          12.0    70
4  17.0          8         302.0       140.0    3449          10.5    70

เปลี่ยน $\texttt{dataframe}$ ให้เป็น numpy array ด้วย $\texttt{dataframe.to_numpy()}$  

1. Response: $\texttt{y}$ เป็นคอลัมน์เวกเตอร์ของ $\texttt{mpg}$
2. Predictors: $\texttt{X}$ เป็นเมทริกซ์ของตัวแปรที่เหลือ (ใช้ $\texttt{auto_df.drop}$)


In [11]:
y = auto_df['mpg'].to_numpy()
X = auto_df.drop(['mpg'],axis=1).to_numpy()

คอลัมน์แรกของ $\texttt{X}$ ต้องเป็น $(1, 1, \ldots ,1 )^T$ (จำนวนเลข 1 เท่ากับจำนวนแถวของ $\texttt{X}$)  
จงสร้างเวกเตอร์ที่มีแต่เลข 1 และมีความยาวที่เหมาะสมด้วยคำสั่งใดคำสั่งหนึ่งต่อไปนี้  
1. $\texttt{[1]*n}$  
2. $\texttt{np.ones(n)}$  

โดยที่ n คือจำนวนแถวของ $\texttt{X}$ (Hint: ใช้ $\texttt{X.shape[0]}$)

In [12]:
n = X.shape[0]

In [13]:
print(X)

[[   8.   307.   130.  3504.    12.    70. ]
 [   8.   350.   165.  3693.    11.5   70. ]
 [   8.   318.   150.  3436.    11.    70. ]
 ...
 [   4.   135.    84.  2295.    11.6   82. ]
 [   4.   120.    79.  2625.    18.6   82. ]
 [   4.   119.    82.  2720.    19.4   82. ]]


In [14]:
#one dimensional array consisting of only 1's
ones = np.ones(auto_df.shape[0])

#ใส่ ones ให้เป็นคอลัมน์แรกของ X
X = np.c_[ones,X]

In [15]:
#เช็คคำตอบ
print(X)

[[1.000e+00 8.000e+00 3.070e+02 ... 3.504e+03 1.200e+01 7.000e+01]
 [1.000e+00 8.000e+00 3.500e+02 ... 3.693e+03 1.150e+01 7.000e+01]
 [1.000e+00 8.000e+00 3.180e+02 ... 3.436e+03 1.100e+01 7.000e+01]
 ...
 [1.000e+00 4.000e+00 1.350e+02 ... 2.295e+03 1.160e+01 8.200e+01]
 [1.000e+00 4.000e+00 1.200e+02 ... 2.625e+03 1.860e+01 8.200e+01]
 [1.000e+00 4.000e+00 1.190e+02 ... 2.720e+03 1.940e+01 8.200e+01]]


หาเวกเตอร์ของสัมประสิทธิ์ $\boldsymbol{\hat\beta}$ ได้จาก
$$ \boldsymbol{\hat\beta} = (X^TX)^{-1}X^Ty $$

ทำนายค่าของตัวแปรตาม ($\boldsymbol{\hat Y}$) โดยใช้

$$ \boldsymbol{\hat Y} = X\boldsymbol{\hat \beta}$$

numpy method ที่ต้องใช้มีดังนี้
1. Matrix multiplication $AB = \texttt{A@B}$
2. Transpose: $X^T = \texttt{X.T}$
3. Inverse: $X^{-1} = \texttt{np.linalg.inv(X)}$

In [16]:
# Let's start by implementing linear regression from scratch
# using numpy linear algebra


def linear_model(X, y):
    """X: เมทริกซ์ของตัวแปรต้น"""
    """y: เวกเตอร์ของตัวแปรตาม"""
    """Return: เวกเตอร์ของ parameter beta จากการสร้าง linear regressions model
    ด้วย Ordinary Least Squares (OLS)"""

    #TODO: fill code here

    beta = (np.linalg.inv(X.T@X)) @ (X.T@y)

    return beta 

def predict(X, beta):
    """beta: array ของสัมประสิทธิ์"""
    """X: เมทริกซ์ของตัวแปรต้น""" 
    """Return: ค่าทำนาย y_pred = X*beta """
    
    return X@beta       #TODO: fill code here

In [17]:
beta = linear_model(X, y)
y_pred = predict(X, beta)

print(beta)

[-1.45352505e+01 -3.29859089e-01  7.67843024e-03 -3.91355574e-04
 -6.79461791e-03  8.52732469e-02  7.53367180e-01]


#### จงหา $n$ (จำนวนแถวของ $\texttt{X}$) และ $p$ (จำนวนตัวแปร) ด้วย method $\texttt{X.shape[...]}$

In [18]:
n = X.shape[0]

p = X.shape[1]-1

print('Number of observations: ',n)
print('Number of variables: ',p)

Number of observations:  392
Number of variables:  6


####วิธีการคำนวณ Residual Standard Error (RSE)  

จาก

$$ \text{RSS} = \sum_{i=1}^n (y_i-\hat{y}_i)^2$$

คำนวณ RSE ได้ดังนี้

$$ \text{RSE} = \sqrt{\frac{RSS}{n-p-1}} $$

In [19]:
#TODO: compute RSS and RSE

RSS = np.sum(np.square(y-y_pred))


RSE = np.sqrt(RSS/(n-p-1))


####วิธีการคำนวณ Standard Error (SE)  
\begin{align*} \text{SE}(\boldsymbol{\hat{\beta}}) &=\text{RSE}\cdot\sqrt{\text{diag}\left( (X^TX)^{-1}\right)} \\
t &= \frac{\hat{\beta}_i}{\text{SE}(\hat{\beta}_i)}
\end{align*}

ใช้คำสั่ง $\texttt{A.diagonal()}$ เพื่อหาสมาชิกในแนวทแยงของ $\texttt{A}$

In [21]:
#TODO: compute the array of standard errors and t-statistics

# array of standard errors: [SE(β₀), SE(β₁), ... , SE(βₚ)]
inv = np.linalg.inv(X.T@X)
SE_beta = RSE*np.sqrt(inv.diagonal())

# array of t-statistics: [t_β₀, t_β₁, ... , t_βₚ]
t = beta / SE_beta

In [22]:
def t_to_p_values(t_statistics):
  """t_statistics: numpy array ของค่า t-statistic ของตัวแปรต่างๆ"""
  """Return: เวกเตอร์ของค่า p-value ของค่า t-statistic ที่ให้มา"""
  return stats.t.sf(np.abs(t_statistics), n-p-1)*2
# Standard error of each variable in X


p = t_to_p_values(t)

print(p)

[2.43774108e-03 3.21216868e-01 2.97331805e-01 9.77450101e-01
 1.41618989e-21 4.03830330e-01 1.41042759e-37]


In [23]:
# Present results
results = pd.DataFrame({'feature': np.r_[['Intercept'], 
                                         auto_df.drop(['mpg'],axis=1).columns.values],
                        'coefficients': beta,
                        'standard_error': SE_beta,
                        't-statistic': t,
                        'p-value': p})

results

feature  coefficients  standard_error  t-statistic       p-value
0     Intercept    -14.535250        4.763882    -3.051136  2.437741e-03
1     cylinders     -0.329859        0.332104    -0.993240  3.212169e-01
2  displacement      0.007678        0.007358     1.043586  2.973318e-01
3    horsepower     -0.000391        0.013837    -0.028284  9.774501e-01
4        weight     -0.006795        0.000670   -10.140877  1.416190e-21
5  acceleration      0.085273        0.102036     0.835721  4.038303e-01
6          year      0.753367        0.052618    14.317630  1.410428e-37

###Exercise: จงใช้ฟังก์ชัน $\texttt{t_to_p_values}$ ข้างบนในการหาว่ามีตัวแปรใดบ้างที่มีค่า p-value น้อยกว่า 0.05 

คำตอบ: Intercept ($\beta_0$), weight, year

#### statsmodels library สามารถคำนวณค่าต่างๆ เหล่านี้ได้ ผลที่แสดงจะคล้ายกับใน R  
#### มีสองวิธึในการทำ linear regression: $\texttt{statsmodels.api.sm.OLS}$ 
#### และ $\texttt{statsmodels.formula.api.smf.ols}$

In [24]:
# The statsmodels library provides a convenient means to get the
# same statistics
import statsmodels.api as sm

X_sm = auto_df.drop(['mpg'], axis=1)
X_sm = sm.add_constant(X)     # add bias constant
y_sm = auto_df['mpg']

# add bias constant; 
#without this the equation turns into y = βx

# syntax is OLS(response, predictor)
model = sm.OLS(y_sm, X_sm).fit()
print(model.summary())

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.809
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     272.2
Date:                Sat, 16 Jan 2021   Prob (F-statistic):          3.79e-135
Time:                        15:17:23   Log-Likelihood:                -1036.5
No. Observations:                 392   AIC:                             2087.
Df Residuals:                     385   BIC:                             2115.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -14.5353      4.764     -3.051      0.0

In [25]:
import statsmodels.formula.api as smf

#syntax is ols(formula, dataset)
model = smf.ols('mpg ~ cylinders + displacement + \
                      horsepower + weight + \
                      acceleration+year', auto_df)
results = model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.809
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     272.2
Date:                Sat, 16 Jan 2021   Prob (F-statistic):          3.79e-135
Time:                        15:17:29   Log-Likelihood:                -1036.5
No. Observations:                 392   AIC:                             2087.
Df Residuals:                     385   BIC:                             2115.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -14.5353      4.764     -3.051   

In [26]:
auto_df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year'],
      dtype='object')